spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: cloudlibrary/rds/auth/mysql
      driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
      username: cloudlibrary/rds/auth/mysql

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    com.cloudlibrary.auth: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400000
---
spring:
  application:
    name: book-sample-local
  config:
    activate:
      on-profile: local

---
spring:
  application:
    name: book-sample-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: book-sample-prod
  config:
    activate:
      on-profile: prod